### PR TITLE
F/test setup

### LINKED ISSUE #57: test setup improvements
Is anyone open for improvements to the test setup? E.g. phpunit as `require-dev`, a `Makefile` etc.? I'll PR it then.

### PR DESCRIPTION
**Pull request by till**
Resolves #57

### CODE REVIEW

**Comment by lsmith77** [comment]
@weierophinney / @Thinkscape is PHP 5.3.3 still a requirement for ZF2? then again we probably only need PHP fixer in one of the builds.

**Comment by till** [comment]
We can also allow failure?

**Comment by lsmith77** [comment]
think its cleaner to just limit the php fixer to one specific build

**Comment by till** [comment]
@lsmith77 Not sure if there is _real_ value in php-cs-fixer. Could also just run locally before you push up code. But yeah, the rest seems to work. :)

**Comment by lsmith77** [comment]
have a look at https://github.com/zendframework/ZendDiagnostics/pull/60

**Pull request merged**
