### PR TITLE
bump to php-amqplib/php-amqplib

### PR DESCRIPTION
**Pull request by aleachjr**
As the `videlalvaro/php-amqplib` library has been abandoned and replaced with `php-amqplib/php-amqplib` need to update this libraries dependencies to be able to avoid namespace collision for apps that include `php-amqplib/php-amqplib`.

### CODE REVIEW

**Comment by aleachjr** [comment]
Not quite sure composer is throwing an SSL error specifically on PHP 5.3.3. Any help here would be appreciated.

**Comment by evdtempel** [comment]
+1

The failed build doesn't seem to be related to these changes [this other PR](https://github.com/zendframework/ZendDiagnostics/pull/70) has the same issue with 5.3.3. The failed build looks like a issue with the environment to me.

**Comment by zf2timo** [comment]
I think the support for 5.3.3 can be dropped.

**Comment by gpkoltermann** [comment]
It would be great if you merge this.

**Comment by lsmith77** [comment]
closing in favor of #83

**Pull request closed without merging**
