### PR TITLE
Fixes #54, lost alias on single check

### LINKED ISSUE #54: Alias of check is lost for single checking
In this loop $alias always will be 0, if $checkAlias is not null
https://github.com/zendframework/ZendDiagnostics/blob/master/src/ZendDiagnostics/Runner/Runner.php#L112

Problem in this line of code:
https://github.com/zendframework/ZendDiagnostics/blob/master/src/ZendDiagnostics/Runner/Runner.php#L106
For example, this will solve this problem:
$checks = $checkAlias ? new ArrayObject(array($checkAlias => $this->getCheck($checkAlias))) : $this->getChecks();

### PR DESCRIPTION
**Pull request by mfpierre**
Fix for issue #54

### CODE REVIEW

**Comment by lsmith77** [comment]
please rebase

**Comment by mfpierre** [comment]
@lsmith77 :white_check_mark:

**Comment by lsmith77** [comment]
would be great if you could also add a test for this

**Comment by mfpierre** [comment]
@lsmith77 Yeah should have done it earlier :+1:

**Comment by lsmith77** [comment]
thanks!

**Pull request merged**
